desc "create app"
lane :create_app do
  create_app_online
end

platform :ios do
  desc "sign"
  lane :signing do
    sync_code_signing #match
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "build"
  lane :build do
    signing
  end
  
  desc "release"
  lane :release do
    build
  end
end
