# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
app_store_connect_api_key(
  key_id: "G6C7L49QFA",
  issuer_id: "5ed6cccb-6b02-4435-a9f0-e76bbbff7012",
  key_filepath: "key.p8"
)

default_platform(:ios)

platform :ios do
  desc "build to TestFlight"
  lane :beta do
    build_app(scheme: "CFiOSExample")
  end
end
