# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


app_store_connect_api_key(
is_key_content_base64: true
)


#default_platform(:ios)

#platform :ios do
#  desc "build to TestFlight"
#  lane :beta do
#    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
#
#    gym(
#     api_key: api_key, 
#    )
#
#    build_app(scheme: "CFiOSExample")
#  end
#end

desc "Create ipa"
 lane :build do
   api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

   #update profiles
#   sync_profiles
   # Increases the build number by 1
   #increment_build_number
   # Creates a signed file
   gym(
     api_key: api_key,
    )
 end
